# Generated by Django 5.2 on 2025-04-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stepanflow', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
