# Generated by Django 5.2 on 2025-04-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azamat', '0002_post1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
