# Generated by Django 5.2 on 2025-04-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azamat', '0003_post1_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post1',
            options={'ordering': ['-created_at']},
        ),
    ]
