# Generated by Django 5.2 on 2025-04-11 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azamat', '0004_alter_post1_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post1',
            new_name='Post',
        ),
    ]
