# Generated by Django 5.2 on 2025-04-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azamat', '0005_rename_post1_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpeg', upload_to='avatars/'),
        ),
    ]
