# Generated by Django 5.2 on 2025-04-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azamat', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/'),
        ),
    ]
