# Generated by Django 5.2 on 2025-04-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azamat', '0009_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
